/**
 * Turns the real captured assets in public/ into a typed TS module the scenes
 * import synchronously. Remotion can fetch from staticFile(), but that means
 * delayRender() plumbing in every scene for data that never changes at runtime;
 * generating a module keeps the scenes pure and the render deterministic.
 *
 * public/ stays the source of truth. Re-run `pnpm data` after replacing any asset.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(join(root, 'public', p), 'utf8');

const run = JSON.parse(read('run.json'));
const evalResult = JSON.parse(read('eval.json'));
const diff = read('diff.txt').replace(/\s+$/, '');

/** Classify each diff line once, here, so DiffView is pure presentation. */
const diffLines = diff.split('\n').map((text) => {
  const kind = text.startsWith('+++') || text.startsWith('---')
    ? 'file'
    : text.startsWith('@@')
      ? 'hunk'
      : text.startsWith('+')
        ? 'add'
        : text.startsWith('-')
          ? 'del'
          : 'ctx';
  return { text, kind };
});

const out = `// GENERATED by scripts/build-data.mjs — do not edit. Run \`pnpm data\`.
// Source: video/public/{run.json,eval.json,diff.txt}

export type DiffKind = 'file' | 'hunk' | 'add' | 'del' | 'ctx';
export interface DiffLine { text: string; kind: DiffKind }

export const RUN = ${JSON.stringify(run, null, 2)} as const;

export const EVAL = ${JSON.stringify(evalResult, null, 2)} as const;

export const DIFF_LINES: DiffLine[] = ${JSON.stringify(diffLines, null, 2)};

export const DIFF_STATS = {
  files: ${diffLines.filter((l) => l.text.startsWith('+++')).length},
  additions: ${diffLines.filter((l) => l.kind === 'add').length},
  deletions: ${diffLines.filter((l) => l.kind === 'del').length},
};
`;

writeFileSync(join(root, 'src/generated/run-data.ts'), out);
console.log(
  `run-data.ts written — ${diffLines.length} diff lines, ` +
    `${out.length} bytes, score ${evalResult.score}`,
);
